version: "3.8"

services:
  database:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - wishlist-network
  backend:
    container_name: wl-backend
    build: ./backend/
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/usr/src/app/src
    depends_on:
      - database
    networks:
      - wishlist-network

volumes:
  pgdata:

networks:
  wishlist-network:
    driver: bridge
